### ISSUE TITLE
Additional fields

### ISSUE THREAD

**Issue by ghost** [Cetis/intelligent-campus#2]
When building the dashboard demonstrator we included additional fields in things like Institution - main address, location (as GeoJSON point or geom), contact details, etc.

Looking at the LA UDD Institution is pretty minimal. Is that because obtaining that other data is possible through the tenant_id?

In terms of building an application additional fields like location are useful but I can see why they're not in this model.

So the question is - is it worth adding those fields or is it OK to put something like "addititional information" field in the application data model and that is a free-form JSON that can include all the application specific fields?

**Comment by alanepaull** [comment]
The LA UDD doesn't need additional information about institution details, because that data isn't used in the LA. We could add new stuff to the IntCamp model and link to institution via tenant_id (the institution's identifier). I guess that institutions *might* get other data via tenant_id themselves, but this doesn't form part of the Jisc LA service, so probably not relevant.

I think it's best, if we can, to be prescriptive about the data we need if it's fixed data related to the institution, rather than free-form JSON. At this stage, I think we should include all the fields that we believe we'll need (mandatory and important, rather than nice-to-haves). We can always drop or add later.

Are you able to indicate the data items? From what you've said above, you're thinking of geoJSON relating at least to the main site; although for most campuses, this would be insufficient. Do we need contact details? If so, which contacts and for what purpose?

Happy to chat this through, so that I can get a clear understanding of the requirements.

**Comment by ghost** [comment]
I was reminded of something Michael said about only storing what is required in the model and nothing more. Additional fields that pertain to delivery of applications built on *this* data model are the responsibilty of the app.

Which is a roundabout way of saying - I agree - lets keep Institution sparse for now. Thanks!
